In [55]:
import pandas as pd
import numpy as np
import re

In [56]:
#import de dados para iniciar a limpeza de base
data = pd.read_csv ('data/attacks.csv', encoding = "ISO-8859-1")

In [57]:
#retirar linhas sem data
data = data[data['Date'].notnull()]

#retirar linhas sem local
data = data[data['Country'].notnull()]

#exibir display completo
pd.set_option ('max_columns',30)
pd.set_option ('max_colwidth',100)

#Drop colunas inuteis no Dataframe
data.drop('Unnamed: 22', axis=1, inplace=True)
data.drop('Unnamed: 23', axis=1, inplace=True)

#Ajuste de substituição de dados 
data['Fatal (Y/N)'].replace('N ','N',inplace=True)
data['Fatal (Y/N)'].replace('Y ','Y',inplace=True)
data['Fatal (Y/N)'].replace('y','Y',inplace=True)
data['Fatal (Y/N)'].replace('n','N',inplace=True)

In [58]:
data['Country'].replace('UNITED ARAB EMIRATES (UAE)','UNITED ARAB EMIRATES',inplace=True)
data['Country'].replace('ST HELENA, British overseas territory','UNITED KINGDOM',inplace=True)
data['Country'].replace('ST. MAARTIN','ST. MARTIN',inplace=True)
data['Country'].replace('ENGLAND','UNITED KINGDOM',inplace=True)
data['Country'].replace('NORTH PACIFIC OCEAN','PACIFIC OCEAN',inplace=True)
data['Country'].replace('MID-PACIFC OCEAN','PACIFIC OCEAN',inplace=True)
data['Country'].replace('SOUTH PACIFIC OCEAN','PACIFIC OCEAN',inplace=True)
data['Country'].replace('SOUTHWEST PACIFIC OCEAN','PACIFIC OCEAN',inplace=True)
data['Country'].replace('MID ATLANTIC OCEAN','ATLANTIC OCEAN',inplace=True)
data['Country'].replace('SOUTH ATLANTIC OCEAN','ATLANTIC OCEAN',inplace=True)
data['Country'].replace('NORTH ATLANTIC OCEAN','ATLANTIC OCEAN',inplace=True)
data['Country'].replace('INDIAN OCEAN?','INDIAN OCEAN',inplace=True)
data['Country'].replace('CEYLON (SRI LANKA)','SRI LANKA',inplace=True)
data['Country'] = data['Country'].str.rstrip() 
data['Country'] = data['Country'].str.upper()

In [59]:
#tratamento de paises
data['Country'].unique ()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'UNITED KINGDOM',
       'SOUTH AFRICA', 'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS',
       'NEW CALEDONIA', 'ECUADOR', 'MALAYSIA', 'LIBYA', 'CUBA',
       'MAURITIUS', 'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS',
       'JAPAN', 'EGYPT', 'COMOROS', 'REUNION', 'FRENCH POLYNESIA',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'FIJI', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'PUERTO RICO', 'ITALY',
       'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'AZORES', 'SOUTH KOREA', 'MALTA',
       'VIETNAM', 'MADAGASCAR', 'PANAMA', 'SOMALIA', 'NEVIS',
       'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL', 'YEMEN',
       'GULF OF ADEN', 'SIERRA LEONE', 'GRAND CAYMAN', 'LIBERIA',
       'VANUATU', 'HONDURAS', 'VENEZUELA', 'SRI LANKA', ' TONGA',
       'URUGUAY', 'INDIA', 'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA',
       'TANZANIA', 'MARSHALL ISLANDS', 'EGYPT / ISRAEL',
       'NORTHERN ARABIAN SEA', 'HONG KONG', 'EL SALVADOR', 'ANGOLA',
       'BERMUDA', 'MONTENEGRO', 'IRAN', 'TUNISIA', 'NAMIBIA', 'PORTUGAL',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'NEW GUINEA', 'RED SEA', 'FEDERATED STATES OF MICRONESIA',
       'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES', 'PERSIAN GULF',
       'RED SEA / INDIAN OCEAN', 'NORTH SEA', 'NICARAGUA',
       'MALDIVE ISLANDS', 'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS',
       'GABON', 'MAYOTTE', 'NORTH ATLANTIC OCEAN', 'THE BALKANS',
       'SUDAN?', 'ARGENTINA', 'MARTINIQUE', 'INDIAN OCEAN', 'GUATEMALA',
       'NETHERLANDS ANTILLES', 'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ',
       'JAVA', ' PHILIPPINES', 'CENTRAL PACIFIC',
       'SOLOMON ISLANDS / VANUATU', 'BAY OF BENGAL', 'SLOVENIA',
       'CURACAO', 'ICELAND', 'ITALY / CROATIA', 'BARBADOS', 'MONACO',
       'GUYANA', 'HAITI', 'SAN DOMINGO', 'IRELAND', 'KUWAIT',
       'REUNION ISLAND', 'FALKLAND ISLANDS', 'CRETE', 'CYPRUS',
       'WEST INDIES', 'BURMA', 'LEBANON', 'PARAGUAY',
       'BRITISH NEW GUINEA', 'CEYLON', 'OCEAN', 'GEORGIA', 'SYRIA',
       'TUVALU', 'GUINEA', 'ANDAMAN ISLANDS',
       'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
       'AFRICA', 'ALGERIA', 'COAST OF AFRICA', 'TASMAN SEA', 'GHANA',
       'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN', 'ROATAN',
       'BETWEEN PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN', 'KOREA',
       'RED SEA?', 'ASIA?'], dtype=object)

In [60]:
# Retirar casa depois do ano da coluna year
data['Year'] = data['Year'].apply(lambda x: str(x).replace('.0',''))

In [61]:
#limpando os anos que estão sem informação
data = data.loc[data['Year']!='nan']

In [62]:
#tratamento de replaces em linhas
data['Sex '].replace('lli','N',inplace=True)
data['Sex '].replace('M ','M',inplace=True)
data['Name'].replace('?brahim Karagöz','Ibrahim Karagöz', inplace=True)
data['Name'].replace('__ Jimenez','Jimenez', inplace=True)

#Limpando espaço no ínicio dos nomes
data['Name'] = data['Name'].str.lstrip()

In [63]:
#filtrando o nome e alterando dado na coluna sexo
data.loc[data['Name']=='Stephen Pettigew' , 'Sex '] = 'M'

In [64]:
data['Sex '].value_counts()

M    5052
F     634
N       2
.       1
Name: Sex , dtype: int64

In [65]:
data.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [66]:
data['First'] = data['Name'].apply(lambda x: str(x)[:1])

In [67]:
def filtro (x):
    '''função coloca flag nas palavras contidas abaixo'''
    if (re.match('[0-9]|male|female|"|a |an ',x,flags=re.IGNORECASE)):
        return (1)
    else:
        return (0)

In [68]:
#transformando a coluna name em string para usar o appy
data['Name']=data['Name'].astype(str)

In [69]:
#cria a coluna de flag e aplica o filtro para a limpeza de dados sem nome
data['Flag']= data['Name'].apply(filtro) + data['First'].apply(filtro)

In [70]:
data.head ()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,First,Flag
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and paddle damaged",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,2018.06.25,2018.06.25,6303.0,J,0
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0,A,0
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,2018.06.09,2018.06.09,6301.0,J,0
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,2018.06.08,2018.06.08,6300.0,m,1
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,2018.06.04,2018.06.04,6299.0,G,0

In [71]:
data['First'].sort_values()

4514    "
717     "
5826    "
5029    "
3502    "
       ..
4868    y
4273    y
4180    y
5892    y
3935    y
Name: First, Length: 6250, dtype: object

In [72]:
#transforma anos em inteiro para utilizar operadores matemáticos
data['Year']=data['Year'].astype(int)

In [73]:
#retira todos os nomes nulos do dataframe
data = data[data['Name'].notnull()]

In [74]:
data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,First,Flag
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and paddle damaged",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,2018.06.25,2018.06.25,6303.0,J,0
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0,A,0
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,2018.06.09,2018.06.09,6301.0,J,0
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,2018.06.08,2018.06.08,6300.0,m,1
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,2018.06.04,2018.06.04,6299.0,G,0

In [75]:
#coloca toda a coluna de iniciais em maiuscul
data['First'] = data['First'].str.upper()

In [76]:
#check de UPPER
data ['First'].value_counts ()

M    1053
J     618
A     526
R     366
C     346
N     337
B     323
S     310
D     297
F     224
T     211
G     210
K     187
L     184
P     171
W     165
E     157
H     130
I      58
2      57
1      56
O      52
V      40
Z      27
Y      26
U      23
5      20
4      19
3      16
"      14
6      11
7       6
Q       4
8       3
9       3
Name: First, dtype: int64

In [77]:
#retira os nomes nulos
data = data.loc[data['Name']!='Nan']

In [78]:
#check dos elementos coluna Flag
data['Flag'].value_counts()

0    5191
1     854
2     205
Name: Flag, dtype: int64

In [79]:
#retira linhas não desejadas na coluna flag
data = data.loc[data['Flag']==0]

In [80]:
data.head ()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,First,Flag
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and paddle damaged",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,2018.06.25,2018.06.25,6303.0,J,0
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0,A,0
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,2018.06.09,2018.06.09,6301.0,J,0
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,2018.06.04,2018.06.04,6299.0,G,0
5,2018.06.03.b,03-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,NaN,"No injury, board bitten",N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.03.b-FlatRock.pdf,2018.06.03.b,2018.06.03.b,6298.0,C,0

In [81]:
data = data.loc[data['Year']>1900]

In [82]:
data.to_csv('base.csv', sep=';')